// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    return $('a').on('touchstart', function(e) {
      return $(this).addClass('touched');
    }).on('touchend touchmove', function(e) {
      return $(this).removeClass('touched');
    });
  });

}).call(this);
