// Generated by CoffeeScript 1.3.1
(function() {
  var exports;

  exports = window;

  $(function() {
    return exports.console = {
      log: function(msg) {
        return $('#console').html(msg);
      }
    };
  });

}).call(this);
