// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    return $(window).on('devicemotion', function(e) {
      var key, keys, x, _i, _len;
      console.log(e.data);
      return;
      x = [];
      keys = ['accelerationIncludingGravity', 'rotationRate', 'acceleration', 'webkitCompassHeading'];
      for (_i = 0, _len = keys.length; _i < _len; _i++) {
        key = keys[_i];
        x.push("" + key + ": " + e[key]);
      }
      return console.log(x.join('<br>'));
    });
  });

}).call(this);
