// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    var touchPointSize;
    touchPointSize = 50;
    return $(document).on('tap', '.draggable', function(e) {
      return $(this).toggleClass('active');
    }).on('touchmove', '.draggable', function(e) {
      console.log("" + ($(e.target).text()) + ": " + e.touches[0].pageX + "," + e.touches[0].pageY);
      e.target.style.left = "" + (e.touches[0].pageX - touchPointSize / 2) + "px";
      return e.target.style.top = "" + (e.touches[0].pageY - touchPointSize / 2) + "px";
    });
  });

}).call(this);
