// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    var $compass;
    $compass = $('#compass');
    return $(window).on('deviceorientation', function(e) {
      if (e.webkitCompassHeading !== 0) {
        $compass.css({
          '-webkit-transform': "rotate(-" + e.webkitCompassHeading + "deg)"
        });
        return location.href = "taucher://compass/" + e.webkitCompassHeading;
      }
    });
  });

}).call(this);
